# Generated by Django 5.0.6 on 2025-08-19 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clickthrough',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clicked_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(protocol='IPv4')),
                ('url_to', models.URLField(blank=True, null=True, verbose_name='To')),
                ('path_from', models.CharField(blank=True, max_length=256, null=True, verbose_name='From')),
            ],
        ),
    ]
