# Generated by Django 5.0.6 on 2025-08-20 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clickthroughs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clickthrough',
            name='hostname',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='clickthrough',
            name='session_id',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Session ID'),
        ),
        migrations.AddField(
            model_name='clickthrough',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clickthrough',
            name='path_from',
            field=models.TextField(blank=True, null=True, verbose_name='From'),
        ),
    ]
