# Generated by Django 5.2.7 on 2026-01-10 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clickthroughs', '0003_campaign_platform_campaignhostname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='suppliers',
        ),
        migrations.AddField(
            model_name='campaign',
            name='parameters',
            field=models.ManyToManyField(blank=True, related_name='campaigns', to='clickthroughs.parameter'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='platform',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='clickthroughs.platform'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='parameter',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='clickthroughs.platform'),
        ),
    ]
