# Generated by Django 5.2.7 on 2026-01-27 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clickthroughs', '0004_remove_campaign_suppliers_campaign_parameters_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
